### ISSUE TITLE
MFCC errors?

### ISSUE THREAD

**Issue by karlhugle** [leozimmerman/ofxAudioAnalyzer#2]
dct_f.assign(10,0 ); 

while numberCoefficients (integer ∈ [1, ∞), default = 13) :  13 is the number of output mel coefficients.
http://essentia.upf.edu/documentation/reference/streaming_MFCC.html

--------
Should it be dct_f.assign(**13**,0 )?

--------
I changed the two line and got 13 coefficients.  keep 2-13 as coefficients, the first is energy? 

dct_f.assign(**13**,0 )?
dct = factory.create("DCT", "inputSize", 24, "outputSize", **13**);

thanks

**Comment by leozimmerman** [comment]
From the Essentia reference I understand that the number of coefficients that the dct algorithm outputs is variable (from 1 to inf). If you change it to 13 you'll get 13 coefficients, if you change it to 30 you will get 30 coef.  I can't remember now why I put 10 instead of 13, it seems I decided to get less coefficients. I must confess that this is an algorithm I didn't have the chance to use it ver much, so I couldn't test all this I'm saying yet.

**Comment by karlhugle** [comment]
Many thanks for explanation
